### PR TITLE
Master database and errors

### LINKED ISSUE #28: Accessing error code from returned error
When performing a `CreateDatabase` where the database already exists, the database returns error code 1207 (https://docs.arangodb.com/3.0/Manual/Appendix/ErrorCodes.html, ERROR_ARANGO_DUPLICATE_NAME).

This error code is wrapped in a [`numberedError`](https://github.com/solher/arangolite/blob/v2.0.1/errors.go#L26) at [https://github.com/solher/arangolite/blob/v2.0.1/database.go#L207](https://github.com/solher/arangolite/blob/v2.0.1/database.go#L207)

However, at the next step, the [`numberedError`](https://github.com/solher/arangolite/blob/v2.0.1/errors.go#L26) is wrapped in a [`statusCodedError`](https://github.com/solher/arangolite/blob/v2.0.1/errors.go#L3) at [https://github.com/solher/arangolite/blob/v2.0.1/database.go#L213](https://github.com/solher/arangolite/blob/v2.0.1/database.go#L213)

The `statusCodedError` is what is returned by `Send`.

My question is how should the error code be accessed?

[`HasErrorNum`](https://github.com/solher/arangolite/blob/v2.0.1/errors.go#L36) will not work, since it requires a `numberedError` as input, and casting to `statusCodedError` to access the `error` attribute doesn't work, since `statusCodedError` is not exported.

Current result of `arangolite.HasStatusCode(err)` is 409, but `arangolite.HasErrorNum(e_status, 1207)` gives false.

### PR DESCRIPTION
**Pull request by bendikro**
Fixes #28 and #30 

Please verify if the fix to database.followCursor() does not break something.

### CODE REVIEW

**Comment by solher** [comment]
Thanks again for taking the time to help here.

About the database modification, my original thought for the `Run` method was just to provide a helper to access the response `result` field easily (all the AQL querying). I thought that everything revolving around administration tasks (or anything where the user would need to access the raw response) would be easier to use directly using the `Send` method. But now that I think about it, I totally get why it can be confusing and I agree that we could probably fallback to unmarshaling the whole raw response when no result is found. It only adds some inconsistency in the behavior of the `Run` method depending on the kind of `Runnable` the user is executing, but I don't think it would be too problematic. The `Run` method should aim at being a helper and work easily in a straightforward manner in 90% of the cases so it definitely makes sense.

About the error modifications, the reason why I did what I did before was to not offuscate the `pkg/errors` errors by adding some concrete implementations on the top of it (with the modifications of this MR, a user would not be able to get the stacktrace or the error cause). But again, now that I think about it, I'm not even sure the use of `pkg/errors` in a library is a good idea and is pertinent. A user **should not** get the stack of an error from an external library anyway. So we should probably even remove `pkg/errors` from Arangolite totally.

About the makefile on the other hand, I'm not totally convinced about the value it brings. Does adding the ability to do `make test TEST_ARGS=TestIsErrUnique` instead of `go test -run TestIsErrUnique` really worths the addition of a new file?

Really glad to have someone to help me cleanup the V2. To be totally honest, it was supposed to be battle tested in a project that actually never happened, so it stayed in a bit of a "beta" status.

**Comment by bendikro** [comment]
Thanks for the quick responses!

I did suspect that I was trying to use Run() for more than what it was meant for. The confusion comes from few examples or docs explaining when to use Run() or Send().
It's really up to you to decide what the best solution is regarding inconsistencies in the behavior of Run(). Simply explaining when the two functions should be used may be enough?

The modifications to errors.go was to get it working properly, but your latest changes [2c21a436](https://github.com/bendikro/arangolite/commit/2c21a43686b19a46543193b8d398f4b3070bb6df) also pass the tests in errors_test.go, so the changes to errors.go can be discarded if you prefer. The tests are nice though :-)

The benefit of the Makefile is that it makes it easy for newcomers not familiar with GO to run the tests as well as the gofmt check. Making it simple for people to do the right thing is my motto :-)

Feel free include only the modifications you find useful!

**Comment by solher** [comment]
The way I see it is that the use of Run() or Send() should not depend on the request but should depend on the level of abstraction the user wants. Run() should work in every case 90% of the time (doing some assumptions to make things simpler) and Send() should be used when the user wants full control over what's happening (in particular unmarshaling and pagination). So I think you're right and falling back to unmarshaling the raw response when no result is present is a very reasonable assumption.

I think I'll keep your errors too, thanks a lot.

I agree with this motto and I don't really see how using a custom makefile makes it more simple for newcomers than using the standard library (even more when it doesn't simplify the commands syntax).

**Comment by bendikro** [comment]
Thanks!

**Pull request merged**
